name: Deploy to PyPI

on:
  push:
    branches:
      - main
    # tags:
    #   - 'v*'

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    environment:
      name: pypi
      url: https://pypi.org/p/kurigram-addons

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install "poetry>=2.0.0"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1